### ISSUE TITLE
[BUG] release_pull runtime error

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/EDMC-Canonn#101]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyc", line 954, in _bootstrap_inner
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn\canonn\release.py", line 78, in run
    self.release.release_pull()
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn\canonn\release.py", line 169, in release_pull
    self.event_generate('<<ReleaseUpdate>>', when='tail')
  File "tkinter\__init__.pyc", line 1858, in event_generate
RuntimeError: main thread is not in main loop

**Comment by NoFoolLikeOne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Placeholder](https://trello.com/c/54LyW36B/17-placeholder)
