### ISSUE TITLE
[BUG] Plotting by targetting in the black causes an error

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/EDMC-Canonn#134]
The issue is that at start jump the coordinates of the system are unknown unless you use navroute to target the systems.

We need to see if we can find another event to provide coordinates or handle the error gracefully.

Need to be surrounded by unknown systems to reproduce and not use routing

2022-06-26 19:38:35.455 UTC - ERROR - 9004:11696:11696 plug.notify_journal_entry:272: Plugin "Canonn" failed
Traceback (most recent call last):
  File "plug.pyc", line 269, in notify_journal_entry
  File "C:\Users\newbo\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.7.0\load.py", line 240, in journal_entry
    x, y, z = Systems.edsmGetSystem(system)
  File "C:\Users\newbo\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.7.0\canonn\systems.py", line 128, in edsmGetSystem
    s["coords"]["x"], s["coords"]["y"], s["coords"]["z"])
TypeError: list indices must be integers or slices, not str

**Comment by NoFoolLikeOne** [comment]
Fixed in 6.8.1
