### ISSUE TITLE
[BUG] Plugin does not load with a fresh install

### ISSUE THREAD

**Issue by millstonebarn** [canonn-science/EDMC-Canonn#137]
**What is your commander name**
Millstonebarn

**What version are you running**
6.8.0

**Describe the bug**
Fresh install. The plugin didn't load as it couldn't find data\EDMC-Canonn.patrol. As a work-around I created a blank file and that fixed it.

When the file was deleted the plug-in still loaded successfully - unknown why; maybe registry entries meant that it didn't check for the file or something.

**To Reproduce**
Unknown - probabably fresh install and remove registry entries?

**Log Files**
2022-06-29 21:16:03.637 UTC - INFO - 12572:22564:22564 plug.Plugin.__init__:47: loading plugin "EDMC-Canonn-6_8_0" from "C:\Users\ed\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.8.0\load.py"
2022-06-29 21:16:03.815 UTC - ERROR - 12572:22564:22564 plug.Plugin.__init__:62: : Failed for Plugin "EDMC-Canonn-6.8.0"
Traceback (most recent call last):
  File "plug.pyc", line 53, in __init__
  File "C:\Users\ed\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.8.0\load.py", line 115, in plugin_start3
    return plugin_start(plugin_dir)
  File "C:\Users\ed\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.8.0\load.py", line 125, in plugin_start
    patrol.CanonnPatrol.plugin_start(plugin_dir)
  File "C:\Users\ed\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.8.0\canonn\patrol.py", line 344, in plugin_start
    shutil.copyfile(defaults, patrol_json)
  File "shutil.pyc", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ed\\AppData\\Local\\EDMarketConnector\\plugins\\EDMC-Canonn-6.8.0\\data\\EDMC-Canonn.patrol'
2022-06-29 21:16:03.822 UTC - ERROR - 12572:22564:22564 plug.load_plugins:159: Failure loading found Plugin "EDMC-Canonn-6.8.0"
Traceback (most recent call last):
  File "plug.pyc", line 157, in load_plugins
  File "plug.pyc", line 53, in __init__
  File "C:\Users\ed\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.8.0\load.py", line 115, in plugin_start3
    return plugin_start(plugin_dir)
  File "C:\Users\ed\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.8.0\load.py", line 125, in plugin_start
    patrol.CanonnPatrol.plugin_start(plugin_dir)
  File "C:\Users\ed\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.8.0\canonn\patrol.py", line 344, in plugin_start
    shutil.copyfile(defaults, patrol_json)
  File "shutil.pyc", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ed\\AppData\\Local\\EDMarketConnector\\plugins\\EDMC-Canonn-6.8.0\\data\\EDMC-Canonn.patrol'

**Comment by NoFoolLikeOne** [comment]
Thanks should be sorted now
