### ISSUE TITLE
[BUG]  Plugin Error

### ISSUE THREAD

**Issue by IamKayrox** [canonn-science/EDMC-Canonn#147]
**What is your commander name**
CMDR Rebecca Asimov

**What version are you running**
6.9.5

**Describe the bug**
System features don't show, only Jumponium data and a small square that says plugin error

**To Reproduce**
I'm not sure, it happen most of the time

**Expected behavior**
System Features showing

**Screenshots**
![image](https://user-images.githubusercontent.com/11013910/190846394-74bebcc6-6a41-415a-b28a-0f44db8b46c4.png)

**Log Files**
```
E:D Market Connector 5.4.1+e1354c3
2022-09-17 07:43:16.904 UTC - ERROR - 21580:26960:26960 <plugins>.EDMC-Canonn-6.9.5.canonn.codex.CodexTypes.refreshPOIData:1506: Plugin Error
2022-09-17 07:43:16.905 UTC - ERROR - 21580:26960:26960 <plugins>.EDMC-Canonn-6.9.5.canonn.codex.CodexTypes.refreshPOIData:1507: local variable 'comparitor' referenced before assignment
2022-09-17 07:43:16.906 UTC - ERROR - 21580:26960:26960 <plugins>.EDMC-Canonn-6.9.5.canonn.codex.CodexTypes.refreshPOIData:1508: local variable 'comparitor' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\IamKa\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.9.5\canonn\codex.py", line 1052, in refreshPOIData
    self.close_bodies(b, bodies, body_code)
  File "C:\Users\IamKa\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-6.9.5\canonn\codex.py", line 2545, in close_bodies
    if distance is not None and distance < comparitor:
UnboundLocalError: local variable 'comparitor' referenced before assignment
```

**Comment by NoFoolLikeOne** [comment]
Thanks. I have a fix ready.

**Comment by NoFoolLikeOne** [comment]
fixed
