### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by EN3RGIX** [canonn-science/EDMC-Canonn#159]
**What is your commander name**
EN3RGIX

**What version are you running**
EDMC-Canonn-6.9.7

**Describe the bug**
Plugin error while in Oronos system. Only Jumponium box displayed.

**To Reproduce**
Enter Oronos system.

**Expected behavior**
System information to be displayed.

**Screenshots**

**Log Files**
KeyError: 'StarSystem'
2023-01-03 15:07:11.404 UTC - INFO - 11940:16520:16520 plugins.inara.new_worker:1583: sending 5 events for EN3RGIX
2023-01-03 15:14:02.688 UTC - ERROR - 11940:12092:12092 <plugins>.EDMC-Canonn-6.9.7.canonn.codex.CodexTypes.getPOIdata:1931: Error getting SAA data
2023-01-03 15:14:11.992 UTC - INFO - 11940:16520:16520 plugins.inara.new_worker:1583: sending 2 events for EN3RGIX
2023-01-03 15:14:24.633 UTC - ERROR - 11940:14948:14948 plug.notify_journal_entry:315: Plugin "ATEL" failed
Traceback (most recent call last):
  File "plug.pyc", line 312, in notify_journal_entry
  File "C:\Users\midni\AppData\Local\EDMarketConnector\plugins\ATEL\load.py", line 192, in journal_entry
    this.system=(format(entry['StarSystem']))

**Additional context**

**Comment by NoFoolLikeOne** [comment]
Interesting that the ATEL plugin failed as well.

If its a problem with the system name then it might be the same condition causing the error for both

**Comment by NoFoolLikeOne** [comment]
Can't find Oronos in EDSM?
