### ISSUE TITLE
[BUG] this stacktrace 

### ISSUE THREAD

**Issue by jnorthrup** [canonn-science/EDMC-Canonn#172]
https://discord.com/channels/164411426939600896/251742967927144449/1086241998190690354

I cannot reproduce this, I decided to pipe the launcher script to /dev/null

I appear to have posted it to a place of write-only traffic, so i thought maybe it would help to post it here

Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/jim/.local/share/EDMarketConnector/plugins/EDMC-Canonn-7.0.2/canonn/patrol.py", line 396, in update_ui
    self.update()
  File "/home/jim/.local/share/EDMarketConnector/plugins/EDMC-Canonn-7.0.2/canonn/patrol.py", line 447, in update
    overlayService.overlayDisplayMessage(
  File "/home/jim/.local/share/EDMarketConnector/plugins/EDMC-Canonn-7.0.2/canonn/overlayserver.py", line 108, in overlayDisplayMessage
    display(data["message"], id, config['color'], config['posx'], config['posy'], config['display_time'], config["header"]
  File "/home/jim/.local/share/EDMarketConnector/plugins/EDMC-Canonn-7.0.2/canonn/overlayserver.py", line 118, in display
    send_message(str(id)+"-header", str(header_text), str(header_color),
  File "/home/jim/.local/share/EDMarketConnector/plugins/EDMC-Canonn-7.0.2/canonn/overlayserver.py", line 172, in send_message
    plug.show_error(f"Need to install the EDMCOverlay plugin: {ex}")
UnboundLocalError: local variable 'ex' referenced before assignment
Traceback (most recent call last):
  File "/home/jim/.local/share/EDMarketConnector/plugins/edmc-L3-37/load.py", line 203, in journal_entry
    module.journal_entry(cmdr, system, station, entry, state)
  File "/home/jim/.local/share/EDMarketConnector/plugins/edmc-L3-37/mats_helper.py", line 358, in journal_entry
    mat = mat_alias[cat_lower][k]
KeyError: 'tg_interdictiondata'

'tg_interdictiondata'

**Comment by NoFoolLikeOne** [comment]
Thanks. Looks like a typo in the error handler which I'll get fixed up.

The root cause for you may be that you may have the overlay option selected in the configuration but don't have the overlay plugin installed. That is what it was trying to tell you

**Comment by NoFoolLikeOne** [comment]
Added to the next release
