### ISSUE TITLE
Release: Fetching... doesn't go away

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/EDMC-Canonn#19]
**What version are you running**
1.7.2

**Describe the bug**
Under some conditions the release section says fetching and doesn't update

**To Reproduce**

Unknown

**Screenshots**
![screenshot](https://cdn.discordapp.com/attachments/282234887933526017/555175169363279882/Screenshot_5389.png "Screenshot")

**Comment by NoFoolLikeOne** [comment]
I think this should be addressed, but let's see

**Comment by NoFoolLikeOne** [comment]
Still recieving some reports of this. So keeping open

**Comment by CMDR-Cometborne** [comment]
Having this issue with both 1.9.0 and 1.9.1.` Have debug enabled, EDMC log shows:

```loading plugin EDMC-Canonn-1_9_1 from "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-1.9.1\load.py"
loading plugin EDSM-RSE from "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\EDSM-RSE\load.py"
loading plugin huttonhelper from "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\huttonhelper\load.py"
2019-03-26 20:55:20.951000 [EDMC-Canonn.1.9.1] Release: UpdateThread
200 GET http://forthemug.com:4567/news.json/0bb99a8a-b602-4191-b483-aa59a7e8f626 ms=227

200 GET http://hot.forthemug.com/live_plugin_version.json ms=189

2019-03-26 20:55:22.017000 [EDMC-Canonn.1.9.1] Latest is null
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyo", line 1541, in __call__
  File "Tkinter.pyo", line 592, in callit
  File "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-1.9.1\canonn\release.py", line 156, in release_update
AttributeError: 'str' object has no attribute 'after'
2019-03-26 20:55:22.666000 [EDMC-Canonn.1.9.1] latest release downloaded
2019-03-26 20:55:23.791000 [EDMC-Canonn.1.9.1] sending client report2019-03-26 20:55:23.791000 [EDMC-Canonn.1.9.1] Patrol download cycle commencing

2019-03-26 20:55:23.793000 [EDMC-Canonn.1.9.1] Patrol: UpdateThread
2019-03-26 20:55:23.793000 [EDMC-Canonn.1.9.1] Download Patrol Data2019-03-26 20:55:23.793000 [EDMC-Canonn.1.9.1] Refresshing Patrol (StartUp)```

(and yes, the new lines after "sending client report" and "Download Patrol Data" are missing in the original log already

**Comment by NoFoolLikeOne** [comment]
Perfect! That is just what I needed!
