### ISSUE TITLE
[BUG] Entering ship before sample animation complete and going to another planet adds the species there

### ISSUE THREAD

**Issue by FalcoGer** [canonn-science/EDMC-Canonn#200]
**What is your commander name**
Yori Vulpes

**What version are you running**
5.23.0

**Describe the bug**
When you complete the 3rd sample of something, the animation takes a while to play out. At the end of the animation, the biological data is added to the database again. If you cancel the animation by entering an SRV and then a ship, or a ship directly, the animation instead finishes when you next go on foot, even on another planet. On that other planet, the bio data is then added to the database, even if that planet does not have that species.

**To Reproduce**
1. Go to some planet with biology
2. Complete 2 scans of something
3. position your SRV very close by near the 3rd scan
4. conduct the 3rd scan and immediately enter the SRV
5. Enter the ship with the SRV, do not get out again on foot
6. Fly to a different planet
7. Exit the ship on foot
8. Take out the genetic sampler
9. The animation for collecting a 3rd sample will now complete
10. Data will be added

**Expected behavior**
Data is only added after a scan, not when completing sampling

**Screenshots**
![image](https://github.com/user-attachments/assets/f83a9d14-54f0-43f1-b2e9-f73b99ca19d3)

**Log Files**
```text
2024-09-25 18:15:33.186 UTC - INFO - 12696:12892:12892 EDMarketConnector.__main__:2079: Startup v5.11.3+9cc4630 : Running on Python v3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:00:00) [MSC v.1938 32 bit (Intel)]
E:D Market Connector 5.11.3+9cc4630
2024-09-25 18:15:33.232 UTC - INFO - 12696:12892:12892 killswitch.fetch_kill_switches:346: Attempting to fetch kill switches
2024-09-25 18:15:33.374 UTC - INFO - 12696:12892:12892 killswitch.parse_kill_switches:419: Kill switches last updated 18 October 2021
2024-09-25 18:15:34.444 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "coriolis" from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
2024-09-25 18:15:34.515 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "eddn" from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
2024-09-25 18:15:34.597 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "edsm" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
2024-09-25 18:15:34.626 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "edsy" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
2024-09-25 18:15:34.641 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "inara" from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
2024-09-25 18:15:34.678 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "spansh_core" from "C:\Program Files (x86)\EDMarketConnector\plugins\spansh_core.py"
2024-09-25 18:15:34.776 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "EDMC-Canonn-5_23_0" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-5.23.0\load.py"
2024-09-25 18:15:35.619 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "EDMCOverlay" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMCOverlay\load.py"
EDMCOverlay: EDMC Ready
Error sending message in plugin_start() : [WinError 10061] No connection could be made because the target machine actively refused it
2024-09-25 18:15:37.707 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "edmc-L3-37" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py"
L3-37 started
2024-09-25 18:15:39.622 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "EDMCHits" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMCHits\load.py"
C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMCHits\load.py:30: DeprecationWarning: get is Deprecated. use the specific getter for your type
  OVERLAY_MESSAGE_DURATION = tk.StringVar(value=config.get(PREFNAME_OVERLAY_DURATION))
C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMCHits\load.py:31: DeprecationWarning: get is Deprecated. use the specific getter for your type
  OVERLAY_HITS_MODE = tk.StringVar(value=config.get(PREFNAME_OVERLAY_HITS_MODE))
2024-09-25 18:15:41.809 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:90: plugin EDMCJumpSpeed disabled
2024-09-25 18:15:41.811 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "edr" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\edr\load.py"
2024-09-25 18:15:47.107 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined SFX at config/user_sfx_config.v1.ini, using config/sfx_config.v1.ini instead.
2024-09-25 18:15:47.199 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: The system language is not accepted for translation, English will be used.
2024-09-25 18:15:47.204 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: The EDMC language parameter is set to custom: lang en.
2024-09-25 18:15:47.204 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: Version 2.8.0
2024-09-25 18:15:47.219 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_config.v9.ini, using config/user_igm_config.v8.ini instead.
2024-09-25 18:15:47.220 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_config.v9.ini or config/user_igm_config.v8.ini, using config/igm_config.v9.ini instead.
2024-09-25 18:15:49.092 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "EDSM-RSE" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDSM-RSE\load.py"
2024-09-25 18:15:49.313 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "HabZone" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\HabZone\load.py"
2024-09-25 18:15:49.393 UTC - INFO - 12696:12892:12892 plug.Plugin.__init__:65: loading plugin "LandingPad" from "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\LandingPad\load.py"
2024-09-25 18:15:49.636 UTC - INFO - 12696:12892:12892 plugins.eddn.EDDNSender.sqlite_queue_v1:211: New 'eddn_queue-v1.db' created
2024-09-25 18:15:50.501 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v4.ini, using config/user_igm_alt_config.v3.ini instead.
2024-09-25 18:15:50.503 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v4.ini or config/user_igm_alt_config.v3.ini, using config/igm_alt_config.v4.ini instead.
2024-09-25 18:15:50.516 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_themed_config.v4.ini, using config/user_igm_alt_themed_config.v3.ini instead.
2024-09-25 18:15:50.516 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_themed_config.v4.ini or config/user_igm_alt_themed_config.v3.ini, using config/igm_alt_themed_config.v4.ini instead.
2024-09-25 18:15:50.518 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v4.ini, using config/user_igm_alt_config.v3.ini instead.
2024-09-25 18:15:50.519 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v4.ini or config/user_igm_alt_config.v3.ini, using config/igm_alt_config.v4.ini instead.
2024-09-25 18:15:50.520 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_themed_config.v4.ini, using config/user_igm_alt_themed_config.v3.ini instead.
2024-09-25 18:15:50.521 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_themed_config.v4.ini or config/user_igm_alt_themed_config.v3.ini, using config/igm_alt_themed_config.v4.ini instead.
2024-09-25 18:15:50.524 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v4.ini, using config/user_igm_alt_config.v3.ini instead.
2024-09-25 18:15:50.525 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_config.v4.ini or config/user_igm_alt_config.v3.ini, using config/igm_alt_config.v4.ini instead.
2024-09-25 18:15:50.526 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_themed_config.v4.ini, using config/user_igm_alt_themed_config.v3.ini instead.
2024-09-25 18:15:50.528 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: No user defined layout at config/user_igm_alt_themed_config.v4.ini or config/user_igm_alt_themed_config.v3.ini, using config/igm_alt_themed_config.v4.ini instead.
C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\HabZone\load.py:225: DeprecationWarning: getint is Deprecated. Use get_int instead
  setting = config.getint('habzone')
Failed to load route data
Chat Viewer loaded
Recon Limpet Controllers is missing!
Research Limpet Controller is missing!
L3-37 loaded
Exception in thread canonn-ReleaseThread:
Traceback (most recent call last):
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-5.23.0\canonn\release.py", line 102, in run
    self.release.release_pull()
  File "C:\Users\Paul\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-5.23.0\canonn\release.py", line 197, in release_pull
    self.event_generate("<<ReleaseUpdate>>", when="tail")
  File "tkinter\__init__.pyc", line 1933, in event_generate
RuntimeError: main thread is not in main loop
2024-09-25 18:15:55.711 UTC - INFO - 12696:12892:12892 monitor.EDLogs.start:251: Monitoring Journal Folder: "D:\Eigene Dateien\My Games\Frontier Developments\Elite Dangerous"
2024-09-25 18:15:55.712 UTC - INFO - 12696:12892:12892 monitor.EDLogs.start:252: Start Journal File: "D:\Eigene Dateien\My Games\Frontier Developments\Elite Dangerous\Journal.2024-09-24T233715.01.log"
2024-09-25 18:15:55.834 UTC - INFO - 12696:12892:12892 update.check_for_fdev_updates:71: FDEV ID file commodity.csv already up to date.
2024-09-25 18:15:55.962 UTC - INFO - 12696:12892:12892 update.check_for_fdev_updates:71: FDEV ID file rare_commodity.csv already up to date.
2024-09-25 18:15:59.813 UTC - WARNING - 12696:5212:5212 monitor.EDLogs.event_valid_engineerprogress:2032: Progress event without 'Rank' key: entry={'timestamp': '2024-09-25T01:00:01Z', 'event': 'EngineerProgress', 'Engineer': 'Petra Olmanova', 'EngineerID': 300130, 'Progress': 'Invited'}
2024-09-25 18:15:59.824 UTC - WARNING - 12696:5212:5212 monitor.EDLogs.event_valid_engineerprogress:1986: EngineerProgress has neither 'Engineers' nor 'Progress': entry={'timestamp': '2024-09-25T01:00:17Z', 'event': 'EngineerProgress', 'Engineer': "Tod 'The Blaster' McQuinn", 'EngineerID': 300260, 'Rank': 4}
2024-09-25 18:15:59.839 UTC - WARNING - 12696:5212:5212 monitor.EDLogs.event_valid_engineerprogress:1986: EngineerProgress has neither 'Engineers' nor 'Progress': entry={'timestamp': '2024-09-25T01:00:40Z', 'event': 'EngineerProgress', 'Engineer': "Tod 'The Blaster' McQuinn", 'EngineerID': 300260, 'Rank': 5}
2024-09-25 18:16:51.205 UTC - INFO - 12696:5212:5212 monitor.EDLogs.worker:466: New Journal File. Was "D:\Eigene Dateien\My Games\Frontier Developments\Elite Dangerous\Journal.2024-09-24T233715.01.log", now "D:\Eigene Dateien\My Games\Frontier Developments\Elite Dangerous\Journal.2024-09-25T201650.01.log"
2024-09-25 18:17:50.608 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1873: Starting shutdown procedures...
2024-09-25 18:17:50.609 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1876: Closing update checker...
2024-09-25 18:17:50.610 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1883: Notifying plugins to stop...
2024-09-25 18:17:50.611 UTC - INFO - 12696:12892:12892 plug.notify_stop:263: Asking plugin "EDDN" to stop...
2024-09-25 18:17:50.614 UTC - INFO - 12696:12892:12892 plug.notify_stop:263: Asking plugin "EDSM" to stop...
2024-09-25 18:17:50.617 UTC - INFO - 12696:12892:12892 plug.notify_stop:263: Asking plugin "Inara" to stop...
2024-09-25 18:17:50.619 UTC - INFO - 12696:12892:12892 plug.notify_stop:263: Asking plugin "Spansh" to stop...
2024-09-25 18:17:50.619 UTC - INFO - 12696:12892:12892 plug.notify_stop:263: Asking plugin "EDMC-Canonn-5.23.0" to stop...
2024-09-25 18:17:50.621 UTC - INFO - 12696:12892:12892 plug.notify_stop:263: Asking plugin "EDMCHits" to stop...
2024-09-25 18:17:50.622 UTC - INFO - 12696:12892:12892 plug.notify_stop:263: Asking plugin "EDMCOverlay" to stop...
2024-09-25 18:17:50.623 UTC - INFO - 12696:12892:12892 plug.notify_stop:263: Asking plugin "edr" to stop...
2024-09-25 18:17:50.624 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: Stopping the plugin...
2024-09-25 18:17:50.956 UTC - INFO - 12696:12892:12892 <plugins>.edr.edrlog.EDRLog.log:32: Plugin stopped
2024-09-25 18:17:50.957 UTC - INFO - 12696:12892:12892 plug.notify_stop:269: Done
2024-09-25 18:17:50.958 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1888: Unregistering hotkey manager...
2024-09-25 18:17:50.960 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1892: Closing CAPI query thread...
2024-09-25 18:17:50.960 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1896: Closing dashboard...
2024-09-25 18:17:50.961 UTC - INFO - 12696:11760:11760 companion.Session.capi_query_worker:977: endpoint __EDMC_WORKER_SHUTDOWN, exiting...
2024-09-25 18:17:50.963 UTC - INFO - 12696:11760:11760 companion.Session.capi_query_worker:1020: CAPI worker thread DONE
2024-09-25 18:17:50.965 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1899: Closing journal monitor...
2024-09-25 18:17:50.973 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1903: Closing protocol handler...
2024-09-25 18:17:50.974 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1906: Closing Frontier CAPI sessions...
2024-09-25 18:17:50.975 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1910: Closing config...
2024-09-25 18:17:50.976 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1913: Destroying app window...
2024-09-25 18:17:51.264 UTC - INFO - 12696:5212:5212 monitor.EDLogs.worker:479: We're not meant to be running, exiting...
2024-09-25 18:17:52.079 UTC - INFO - 12696:12892:12892 EDMarketConnector.AppWindow.onexit:1916: Done.
2024-09-25 18:17:52.080 UTC - INFO - 12696:12892:12892 EDMarketConnector.__main__:2332: Exiting
```

**Additional context**
The `Cactoida Perperatis` data on `B3` in `Agnairy XC-D c28-827` was added falsely after the animation completed after scanning it on B2. The `Cactoida Cortexum` is the correct genus for `B3`.

**Comment by FalcoGer** [comment]
You may want to check if a landing on a different planet has occurred.

```text
{ "timestamp":"2024-10-07T12:34:35Z", "event":"Touchdown", "PlayerControlled":true, "Taxi":false, "Multicrew":false, "StarSystem":"Agnairy XC-D c28-827", "SystemAddress":227402915161330, "Body":"Agnairy XC-D c28-827 B 3", "BodyID":17, "OnStation":false, "OnPlanet":true, "Latitude":-5.909768, "Longitude":-158.023361 }
```

and later check against the system and body when the late sample occurs

```text
{ "timestamp":"2024-10-07T12:35:27Z", "event":"ScanOrganic", "ScanType":"Analyse", "Genus":"$Codex_Ent_Cactoid_Genus_Name;", "Genus_Localised":"Cactoida", "Species":"$Codex_Ent_Cactoid_05_Name;", "Species_Localised":"Cactoida Peperatis", "Variant":"$Codex_Ent_Cactoid_05_L_Name;", "Variant_Localised":"Cactoida Peperatis - Mauve", "SystemAddress":227402915161330, "Body":16 }
```

Note that the body id is still from the old planet.

[Journal.2024-10-07T113932.01.log](https://github.com/user-attachments/files/17279651/Journal.2024-10-07T113932.01.log)


I have also noted that another position entry is made for finalizing the sample, even though a position entry was already made for finishing the last scan. Maybe you just want to omit that entirely since where you are at that time has no relation to where any of the biologicals are.

**Comment by NoFoolLikeOne** [comment]
I'll change the code so we don't  display it on the next system. When sending data we ignore the final event for this very reason,

**Comment by FalcoGer** [comment]
Okay. Feel free to close whenever you're done then.
Thank you for your time.
