### ISSUE TITLE
Legacy Code not working in unicode regions

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/EDMC-Canonn#29]
**What version are you running**
1.9.0

**Describe the bug**
Codex entries in regions with commas in the name generate an error when they are logged. 
This is because the unicode doesnt play nicely

**To Reproduce**
Fly to any of the following regions and trigger a codex event

Ryker's Hope
Odin's Hold
Newton's Vault
Hawking's Gap
Dryman's Point
Aquila's Halo
Achilles's Altar
Lyra's Song
Kepler's Crest

** Log Files **

[Log file](https://drive.google.com/open?id=1AgXuOTcZDx1Q_1OCJy8J47621CkjBkvY)

```
Traceback (most recent call last):
  File "plug.pyo", line 302, in notify_journal_entry
  File "C:\Users\DOOM\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-1.9.0\load.py", line 141, in journal_entry
  File "C:\Users\DOOM\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-1.9.0\load.py", line 156, in journal_entry_wrapper
  File "C:\Users\DOOM\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-1.9.0\canonn\legacy.py", line 79, in CodexEntry
  File "urllib.pyo", line 1303, in quote_plus
  File "urllib.pyo", line 1298, in quote
KeyError: u'\u2019'
```

**Additional context**

**Comment by NoFoolLikeOne** [comment]
in release 1.9.1
