### ISSUE TITLE
[BUG] getShipType AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/EDMC-Canonn#57]
WentbackwardToday at 6:10 AM
Hi ... having some problems with EDMC crashing out which meant my faction kills not updating ... have not narrowed down any particular cause but during debug noticed these errors in the logs 2019-07-20 12:26:04.643000 [EDMC-Canonn.2.3.0] Suhte: Canonn Influence 31.37% States: civilliberty Please complete missions for Canonn to increase our influence
Traceback (most recent call last):
  File "plug.pyo", line 365, in notify_newdata
  File "C:\Users\paul\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-2.3.0\load.py", line 226, in cmdr_data
  File "C:\Users\paul\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-2.3.0\canonn\patrol.py", line 776, in cmdr_data
  File "C:\Users\paul\AppData\Local\EDMarketConnector\plugins\EDMC-Canonn-2.3.0\canonn\patrol.py", line 98, in getShipType
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by raysanders** [comment]
Discussed in Discord.  https://github.com/canonn-science/EDMC-Canonn/pull/59 Should fix this. Feel free to pull from my branch and test before promoting to prod.

**Comment by NoFoolLikeOne** [comment]
PR accepted.
