### ISSUE TITLE
Odin's Hold Not Logging

### ISSUE THREAD

**Issue by NoFoolLikeOne** [canonn-science/EDMC-Canonn#8]
Traceback (most recent call last):
  File "plug.pyo", line 302, in notify_journal_entry
  File "C:\Users\reneo\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py", line 938, in journal_entry
  File "C:\Users\reneo\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py", line 957, in journal_entry_wrapper
  File "C:\Users\reneo\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py", line 1071, in CodexEntry
  File "urllib.pyo", line 1303, in quote_plus
  File "urllib.pyo", line 1298, in quote
KeyError: u'\u2019'

Looks like unicode issues

{ "timestamp":"2019-01-12T01:39:17Z", "event":"Music", "MusicTrack":"Codex" }
{ "timestamp":"2019-01-25T22:46:36Z", "event":"CodexEntry", "EntryID":1301801, "Name":"$Codex_Ent_Standard_Ter_Ice_Name;", "Name_Localised":"Non Terraformable", "SubCategory":"$Codex_SubCategory_Terrestrials;", "SubCategory_Localised":"Terrestrial planets", "Category":"$Codex_Category_StellarBodies;", "Category_Localised":"Astronomical Bodies", "Region":"$Codex_RegionName_4;", "Region_Localised":"Odin’s Hold", "System":"Dryooe Prou HD-X b48-62", "SystemAddress":136876714968993, "IsNewEntry":true }

**Comment by NoFoolLikeOne** [comment]
Looks like I might need to use this when sending the json

`json.dumps(u"ברי צקלה", ensure_ascii=False).encode('utf8')`

**Comment by NoFoolLikeOne** [comment]
This has now been added to the emitter

**Comment by NoFoolLikeOne** [comment]
Testing needed at 

Ryker's Hope
Odin's Hold
Newton's Vault
Hawking's Gap
Dryman's Point
Aquila's Halo
Achilles's Altar
Lyra's Song
Kepler's Crest

**Comment by NoFoolLikeOne** [comment]
The issues is no longer affecting strapi but still affecting the google sheets in the legacy. Will close this and open a new issue for legacy
